### ISSUE TITLE
I found your work on Deno showcase, however you don't include a license so the default applies

### ISSUE THREAD

**Issue by dnk8n** [mooxl/fresh.mooxl.dev#1]
without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work

It would be great to use your work as a starting point. May I please?

**Comment by mooxl** [comment]
Hey @dnk8n,
added a MIT license to the project:)

**Comment by dnk8n** [comment]
Lightning fast, are you running on deno too!? Thank you so much :)

**Comment by mooxl** [comment]
Yes, the site is running on Deno Deploy!
